version: '3.8'

services:
  redis-master:
    image: redis:6-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  redis-slave:
    image: redis:6-alpine
    container_name: redis-slave
    command: redis-server --slaveof redis-master 6379 --appendonly yes
    depends_on:
      - redis-master
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  redis-master-data:
