version: "3"

services:
  gitea-server:
    image: gitea/gitea:1.13.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "222:22"
