version: '3.1'

services:
  mongo:
    image: mongo:7.0.5-rc0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "example", "--eval", "db.stats()"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
